// Package workflow contains Temporal workflow definitions.
package workflow

import (
	"fmt"
	"strings"

	"github.com/tinkerloft/fleetlift/internal/model"
)

// generateAgentsMD creates the AGENTS.md content for the workspace.
func generateAgentsMD(task model.Task) string {
	var sb strings.Builder

	sb.WriteString("# Agent Instructions\n\n")
	sb.WriteString(fmt.Sprintf("## Task: %s\n\n", task.Title))
	sb.WriteString(fmt.Sprintf("**Task ID:** %s\n\n", task.ID))

	if task.Execution.Agentic != nil && task.Execution.Agentic.Prompt != "" {
		sb.WriteString(fmt.Sprintf("**Prompt:**\n%s\n\n", task.Execution.Agentic.Prompt))
	}

	if task.TicketURL != nil {
		sb.WriteString(fmt.Sprintf("**Related Ticket:** %s\n\n", *task.TicketURL))
	}

	// Include transformation repo info if set
	if task.UsesTransformationRepo() {
		sb.WriteString("## Transformation Repository\n\n")
		sb.WriteString("This workspace uses a transformation repository with skills and tools.\n")
		sb.WriteString(fmt.Sprintf("- Transformation: `%s` (branch: %s)\n\n", task.Transformation.Name, task.Transformation.Branch))
	}

	sb.WriteString("## Repositories\n\n")
	effectiveRepos := task.GetEffectiveRepositories()
	for _, repo := range effectiveRepos {
		if task.UsesTransformationRepo() {
			sb.WriteString(fmt.Sprintf("- `%s` (branch: %s) - located at `/workspace/targets/%s`\n", repo.Name, repo.Branch, repo.Name))
		} else {
			sb.WriteString(fmt.Sprintf("- `%s` (branch: %s)\n", repo.Name, repo.Branch))
		}
	}

	sb.WriteString("\n## Guidelines\n\n")
	sb.WriteString("1. Focus on the specific task described above\n")
	sb.WriteString("2. Make minimal, targeted changes\n")
	sb.WriteString("3. Follow existing code style and patterns\n")
	sb.WriteString("4. Add tests if applicable\n")
	sb.WriteString("5. Do not modify unrelated files\n")

	return sb.String()
}

// getRepoPath returns the path to a repository within the workspace.
// When using transformation mode, repos are in /workspace/targets/{name}.
// Otherwise, repos are in /workspace/{name}.
func getRepoPath(task model.Task, repo model.Repository) string {
	if task.UsesTransformationRepo() {
		return fmt.Sprintf("/workspace/targets/%s", repo.Name)
	}
	return fmt.Sprintf("/workspace/%s", repo.Name)
}

// hasSchema checks if the task has a JSON Schema defined for report validation.
func hasSchema(task model.Task) bool {
	return task.Execution.Agentic != nil &&
		task.Execution.Agentic.Output != nil &&
		len(task.Execution.Agentic.Output.Schema) > 0
}

// buildPRDescriptionWithFiles creates the PR description with a list of modified files.
func buildPRDescriptionWithFiles(task model.Task, filesModified []string) string {
	var sb strings.Builder

	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("Automated fix for: %s\n\n", task.Title))

	if task.Execution.Agentic != nil && task.Execution.Agentic.Prompt != "" {
		sb.WriteString(fmt.Sprintf("**Original prompt:**\n%s\n\n", task.Execution.Agentic.Prompt))
	}

	if task.TicketURL != nil {
		sb.WriteString(fmt.Sprintf("**Related ticket:** %s\n\n", *task.TicketURL))
	}

	// Add transformation mode info
	if task.Execution.GetExecutionType() == model.ExecutionTypeDeterministic {
		sb.WriteString(fmt.Sprintf("**Transformation:** Deterministic (%s)\n\n", task.Execution.Deterministic.Image))
	}

	sb.WriteString("## Changes\n\n")
	if len(filesModified) > 0 {
		sb.WriteString("Modified files:\n")
		for _, f := range filesModified {
			sb.WriteString(fmt.Sprintf("- `%s`\n", f))
		}
	}

	sb.WriteString("\n---\n")
	sb.WriteString("*This PR was automatically generated by Claude Code Orchestrator*\n")

	return sb.String()
}
